name: Update README stats

on:
  schedule:
    - cron: "0 * * * *"   
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Stats
        run: |
          curl -H "Authorization: token ${{ secrets.PAT_1 }}" \
            "https://github-readme-stats.vercel.app/api?username=jms987&count_private=true&show_icons=true&theme=radical" \
            -o stats.svg

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git pull --rebase origin main
          git add stats.svg
          git commit -m "Update stats" || echo "No changes to commit"
          git push origin main
